### PR TITLE
DogeGarden Landing v2 (to staging)

### PR DESCRIPTION
**Pull request by ryanhaticus**
This is a new version for a potential landing page for [DogeGarden](https://dogegarden.xyz/) built on NextJS (React framework) and TailwindCSS. The tooling used allows for impeccable page performance and easy to read code.

For a preview, please see [my preview](https://dogegarden-landing.vercel.app/) and checkout my fork.

### CODE REVIEW

**Comment by justmedev** [comment]
Doesn't fit too well with the stats page design. Its like two worlds.

**Comment by ryanhaticus** [comment]
> Doesn't fit too well with the stats page design. Its like two worlds.

/shrug, it doesn't have to be exactly the same. Nonetheless, it could be rebuilt, if need be.

**Comment by justmedev** [comment]
> 
> 
> > Doesn't fit too well with the stats page design. Its like two worlds.
> 
> /shrug, it doesn't have to be exactly the same. Nonetheless, it could be rebuilt, if need be.

Well yes but the current one is good enough. This looks more like a startup website for some shop and not like a API for developers.

**Comment by justmedev** [comment]
And its lightmode xD

**Comment by crispyaus** [comment]
Looks great, the first image can be touched up in photo shop to remove some stuff, but later.

**Pull request merged**
